### ISSUE TITLE
Is this plugin working with dart 2?

### ISSUE THREAD

**Issue by salujaharkirat** [spacedragon/graphql-fetch#6]
I am trying to using this plugin with flutter which uses dart2. 

I am getting following error:-

```
NoSuchMethodError: The getter 'name' was called on null.
```

On debugging found that this error is thrown  in generator.dart file.

```
    final library = new File((FileBuilder b) {
       _fragments.forEach((f) => f.generate(path, b));
      _operations.forEach((o) => o.generate(path, b));
    });
```

**Comment by spacedragon** [comment]
I currently stop using dart.  Please fork and modify this repository as you like.

**Comment by salujaharkirat** [comment]
thanks much for the reply @spacedraco . It would be great if you could share a sample output file for a small query. I can pick it up from there :)
